export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Home() {
  return (
    <>
      {/*
        <p className="mt-[500] min-w-[50%]">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
          feugiat turpis faucibus, viverra enim nec, convallis velit.
          Suspendisse potenti. Donec rhoncus placerat massa in pulvinar.
          Interdum et malesuada fames ac ante ipsum primis in faucibus.
          Phasellus scelerisque turpis tellus, ac bibendum ligula sagittis in.
          Quisque eget dolor pharetra, hendrerit enim non, euismod justo. Ut
          vulputate efficitur nibh quis euismod.
        </p>
        */}
    </>
  );
}
