export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Home() {
  return (
    <div className="pointer-events-none relative h-full flex flex-col justify-center content-around flex-wrap text-[#dadfe2] text-center gap-8 ">
      <h1 className="text-9xl">Irene Clemente Aracil</h1>
      <h2 className="text-4xl">Multimedia Engineer</h2>
    </div>
  );
}
