import Image from "next/image";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Home() {
  return (
    <div className="font-[family-name:var(--font-geist-sans)] bg-[url('/hero-template.jpg')] bg-fixed min-h-screen">
      <header className="">
        <div className="">
          <nav
            className="
            flex justify-end gap-10 
            m-0 mt-2 px-5
            absolute right-0 left-0 z-10
            font-semibold text-[#dadfe2]
          "
          >
            <a className="mr-auto">HOME</a>
            <a>ABOUT</a>
            <span className="font-black">•</span>
            <a>PROJECT</a>
            <span className="font-black">•</span>
            <a>CONTACT</a>
          </nav>
        </div>
      </header>
      <main className="min-h-screen content-center">
        {/*
        <p className="mt-[500] min-w-[50%]">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
          feugiat turpis faucibus, viverra enim nec, convallis velit.
          Suspendisse potenti. Donec rhoncus placerat massa in pulvinar.
          Interdum et malesuada fames ac ante ipsum primis in faucibus.
          Phasellus scelerisque turpis tellus, ac bibendum ligula sagittis in.
          Quisque eget dolor pharetra, hendrerit enim non, euismod justo. Ut
          vulputate efficitur nibh quis euismod.
        </p>
        */}
      </main>
      <footer className="bg-[#28375d]/75 text-[#dadfe2] py-5 bottom-0 text-center">
        {/*<p>TODO: Same sections as navbar</p>*/}
        <div className="flex flex-row space-x-5 pb-2 content-center justify-center">
          <a
            href="https://www.linkedin.com/in/irene-clemente-aracil"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              src="/linkedin.svg"
              alt="linkedin logo"
              height={32}
              width={32}
            />
          </a>
          <a
            href="https://github.com/irenecats"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              src="/github.svg"
              alt="linkedin logo"
              height={32}
              width={32}
            />
          </a>
        </div>
        <small>
          &#9400; Copyright 2018, Irene Clemente Aracil. All rights reserved
        </small>
      </footer>
    </div>
  );
}
